### PR TITLE
unirecfilter: do not assume quotes around ip6addrs.

### PR DESCRIPTION
**Pull request by qha**
Also add build artifacts to .gitignore and repair specfile.

### CODE REVIEW

**Comment by qha** [comment]
Please don't merge this yet, there seems to be a bug...

**Comment by cejkato2** [comment]
Ok, we are gonna wait for your notification :-)

**Comment by qha** [comment]
False alarm, i just failed to convince rpm to install the new package.

**Comment by cejkato2** [comment]
Really? No bug? So we can merge it, right?

**Comment by qha** [comment]
Yes. No bug that i can see. Please merge if you see fit!

**Pull request merged**
